import 'package:a2a/a2a.dart' as a2a;
import 'package:equatable/equatable.dart';

/// Represents the lifecycle state of a task in the A2A protocol.
enum TaskLifecycleState {
  /// The task has been submitted and is awaiting execution.
  submitted,

  /// The agent is actively working on the task.
  working,

  /// The task is paused and waiting for input from the user.
  inputRequired,

  /// The task has been successfully completed.
  completed,

  /// The task has been canceled by the user.
  canceled,

  /// The task failed due to an error during execution.
  failed,

  /// The task was rejected by the agent and was not started.
  rejected,

  /// The task requires authentication to proceed.
  authRequired,

  /// The task is in an unknown or indeterminate state.
  unknown,
}

/// Maps A2A task state to our internal TaskLifecycleState enum.
TaskLifecycleState mapA2ATaskState(a2a.A2ATaskState? state) {
  if (state == null) return TaskLifecycleState.unknown;

  switch (state) {
    case a2a.A2ATaskState.submitted:
      return TaskLifecycleState.submitted;
    case a2a.A2ATaskState.working:
      return TaskLifecycleState.working;
    case a2a.A2ATaskState.inputRequired:
      return TaskLifecycleState.inputRequired;
    case a2a.A2ATaskState.completed:
      return TaskLifecycleState.completed;
    case a2a.A2ATaskState.canceled:
      return TaskLifecycleState.canceled;
    case a2a.A2ATaskState.failed:
      return TaskLifecycleState.failed;
    case a2a.A2ATaskState.rejected:
      return TaskLifecycleState.rejected;
    case a2a.A2ATaskState.authRequired:
      return TaskLifecycleState.authRequired;
    case a2a.A2ATaskState.unknown:
      return TaskLifecycleState.unknown;
  }
}

/// Represents a message part within a task status.
class TaskMessagePart extends Equatable {
  const TaskMessagePart({
    required this.text,
    required this.timestamp,
  });

  /// The text content of this message part
  final String text;

  /// When this message part was received
  final DateTime timestamp;

  @override
  List<Object?> get props => [text, timestamp];
}

/// Represents a single task tracked through its lifecycle.
///
/// A2A Protocol - Task Concept:
/// In A2A, a Task is NOT a conversation message. It's the agent's internal
/// work process that may or may not result in a conversational response.
///
/// Key Distinctions:
/// 1. Task Status Messages != Conversation Messages
///    - Status messages are thinking steps ("Loading...", "Processing...")
///    - They show what the agent is doing internally
///    - They are NOT displayed as chat bubbles
///
/// 2. Task Artifacts != Messages
///    - Artifacts are files, data, images generated by the agent
///    - They are downloadable, persistent outputs
///    - They can exist without any conversational response
///
/// 3. Agent Messages (A2AMessage) = Conversation
///    - These are actual responses in the chat
///    - "I've analyzed your data" or "Here's the report"
///    - May or may not accompany task completion
///
/// Example Flow:
///   User: "Generate sales report"
///   → Task created (taskId: "123")
///   → Status: working, message: "Loading data..." (NOT conversation)
///   → Status: working, message: "Generating PDF..." (NOT conversation)
///   → Artifact: report.pdf (downloadable output)
///   → Status: completed
///   → Optional A2AMessage: "Report generated!" (conversation)
///
/// Each task has a unique ID and progresses through different states.
/// Tasks can have multiple status updates (thinking steps) and artifacts.
class TaskInfo extends Equatable {
  const TaskInfo({
    required this.taskId,
    required this.contextId,
    this.state = TaskLifecycleState.unknown,
    this.statusMessages = const [],
    this.artifacts = const [],
    this.errorMessage,
    this.isFinal = false,
    this.lastUpdated,
  });

  /// Unique identifier for this task
  final String taskId;

  /// Context ID for grouping related tasks
  final String contextId;

  /// Current lifecycle state of the task
  final TaskLifecycleState state;

  /// List of status update messages (thinking steps) for this task
  final List<TaskMessagePart> statusMessages;

  /// List of artifacts generated by this task
  final List<a2a.A2AArtifact> artifacts;

  /// Error message if task failed
  final String? errorMessage;

  /// Whether this is the final update for this task (end=true)
  final bool isFinal;

  /// Last time this task was updated
  final DateTime? lastUpdated;

  /// Returns true if the task is in a terminal state
  bool get isTerminal =>
      state == TaskLifecycleState.completed ||
      state == TaskLifecycleState.failed ||
      state == TaskLifecycleState.canceled ||
      state == TaskLifecycleState.rejected;

  /// Returns true if the task is actively being worked on
  bool get isActive =>
      state == TaskLifecycleState.working ||
      state == TaskLifecycleState.submitted;

  @override
  List<Object?> get props => [
        taskId,
        contextId,
        state,
        statusMessages,
        artifacts,
        errorMessage,
        isFinal,
        lastUpdated,
      ];

  /// Creates a copy of this TaskInfo with updated fields
  TaskInfo copyWith({
    String? taskId,
    String? contextId,
    TaskLifecycleState? state,
    List<TaskMessagePart>? statusMessages,
    List<a2a.A2AArtifact>? artifacts,
    String? errorMessage,
    bool? isFinal,
    DateTime? lastUpdated,
  }) {
    return TaskInfo(
      taskId: taskId ?? this.taskId,
      contextId: contextId ?? this.contextId,
      state: state ?? this.state,
      statusMessages: statusMessages ?? this.statusMessages,
      artifacts: artifacts ?? this.artifacts,
      errorMessage: errorMessage ?? this.errorMessage,
      isFinal: isFinal ?? this.isFinal,
      lastUpdated: lastUpdated ?? this.lastUpdated,
    );
  }
}
